CFLAGS = -Wall	-Wextra	-Werror 

my_mastermind : myMastermind.c	functions.c
	gcc $(CFLAGS) -o myMastermind myMastermind.c functions.c

	
clean:
	rm -f myMastermind myMastermind.c functions.c


